### ISSUE TITLE
Feedback exercise 4

### ISSUE THREAD

**Issue by Nadine2016** [IBM/istio101#52]
1. In general, I found this exercise very confusing as you start with the Istio Ingress, then go to the IBM-provided Ingress. I kind of realized that very late in the steps that this was what I was doing. Is there a specific reason why you want both things in this exercise? I could see just using the IBM-provided Ingress and spend some more time on explaining what the benefits are for Ingress compared to what you did in exercise 3. This would also help the user understand what exactly they are doing and why they would want that. 
2. I was also wondering about the non-IBM ingress. The public IP that is assigned, I assume is assigned from our VLANs? if so,  this requires a standard cluster as well, otherwise you do not have portable public IP addresses assigned to the cluster. So not only a paid account is required, it is a standard cluster activity. Free clusters can only use nodeport. 
3. In the IBM-provided Ingress, step 1: why are you looking at the secret when the Ingress does not use the secret?
4. A link to the next exercise is missing at the end

**Comment by linsun** [comment]
1. because it is common these two are used together when you have a paid cluster.

2. Yes, that should be clarified and update instruction with free tier using node-port.

3. Because that is needed if you need to access the app using https.  @szihai , i think Nadine has a good point here, it is probably good to clarify that and show an example of accessing it via https.

**Comment by linsun** [comment]
@szihai any more work related to this one?

**Comment by szihai** [comment]
No, not really. I think some other issues not addressed by my previous PR is out of scope of this workshop.
